export const AVALIABLE_EXAMES: Exame[] = [
  { id: 1, nome: "Covid-19", descricao: "..." },
  { id: 2, nome: "Hepatite B", descricao: "..." },
  { id: 3, nome: "Hepatite C", descricao: "..." },
  { id: 4, nome: "Hepatite D", descricao: "..." },
  { id: 5, nome: "Hepatite E", descricao: "..." },
  { id: 6, nome: "Gripe A", descricao: "..." },
  { id: 7, nome: "Zika Vírus", descricao: "..." },
  { id: 8, nome: "Dengue", descricao: "..." },
  { id: 9, nome: "Chikungunya", descricao: "..." },
  { id: 10, nome: "Febre Amarela", descricao: "..." },
  { id: 11, nome: "HIV", descricao: "..." },
  { id: 12, nome: "Tuberculose", descricao: "..." },
  { id: 13, nome: "Sífilis", descricao: "..." },
  { id: 14, nome: "Malária", descricao: "..." },
  { id: 15, nome: "Sarampo", descricao: "..." },
  { id: 16, nome: "Rubéola", descricao: "..." },
  { id: 17, nome: "Catapora", descricao: "..." },
  { id: 18, nome: "Leptospirose", descricao: "..." },
  { id: 19, nome: "Toxoplasmose", descricao: "..." },
  { id: 20, nome: "Câncer de Mama", descricao: "..." },
];
