import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
import "primereact/resources/themes/lara-light-cyan/theme.css";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Akin LIS",
  description: "Generated by Akin LIS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <PrimeReactProvider>
        <body className={inter.className + " bg-akin-cosmic-latte text-gray-700"}>
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  );
}
